#!/bin/bash

if tmux has-session -t "$RTGREP_PATH" >/dev/null 2>/dev/null; then
  if [[ "$1" == "--kill" ]]; then
    kill $(cat "${RTGREP_PATH}_pid")
    tmux kill-session -t "$RTGREP_PATH" >/dev/null
    exit
  fi
  kill -HUP $(cat "${RTGREP_PATH}_pid")
  tmux attach-session -t "$RTGREP_PATH" >/dev/null
else
  CMD="RTGREP_MAP_KIND=1 rtgrep $@"
  if [[ "$RTGREP_TAGGER" != "" ]]; then
    CMD="RTGREP_TAGGER=\"$RTGREP_TAGGER\" $CMD"
  fi
  if [[ "$RTGREP_PATH" != "" ]]; then
    CMD="RTGREP_PATH=\"$RTGREP_PATH\" $CMD"
  fi
  if [[ "$RTGREP_MAP_KIND" != "" ]]; then
    CMD="RTGREP_MAP_KIND=\"$RTGREP_MAP_KIND\" $CMD"
  fi
  tmux new-session -s "$RTGREP_PATH" "$CMD" >/dev/null
fi

