#!/bin/bash

PATHS=("$@")
RTGREP_PATH="${PATHS[${#PATHS[@]}-1]}"
unset PATHS[${#PATHS[@]}-1]

if tmux has-session -t "$RTGREP_PATH" >/dev/null 2>/dev/null; then
  if [[ "${PATHS[0]}" == "--kill" ]]; then
    kill $(cat "${RTGREP_PATH}_pid")
    tmux kill-session -t "$RTGREP_PATH" >/dev/null
    exit
  fi
  kill -HUP $(cat "${RTGREP_PATH}_pid")
  tmux attach-session -t "$RTGREP_PATH" >/dev/null
else
  CMD="TERM=screen-256color RTGREP_PATH=\"$RTGREP_PATH\" RTGREP_MAP_KIND=1 ~/key/rtgrep/rtgrep ${PATHS[@]}"
  tmux new-session -s "$RTGREP_PATH" "$CMD" >/dev/null
fi

